image: registry.git.ryuu.technology/docker/gitlabrunners/phpcomposer:latest

services:
  - docker:dind

stages:
- build
- test

variables:
#    CONTAINER_IMAGE: $CI_REGISTRY/docker/gitlabrunners/phpcomposer
#    CONTAINER_IMAGE: registry.git.ryuu.technology/$CI_PROJECT_PATH
    VERSION_MAJOR: 0
    VERSION_MINOR: 0
    VERSION_PATCH: 0

before_script:
- echo CI_RUNNER_ID=$CI_RUNNER_ID
- echo CI_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME
- export VERSION=${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}+${CI_PIPELINE_ID}

build:
    stage: build
    artifacts:
        paths:
        - ./vendor/
    script:
    - composer install
    
test:
    stage: test
    artifacts:
        paths:
        - ./vendor/
    script:
    - ./vendor/bin/phpunit --coverage-text --colors=never
    - echo "Tagging version with: v${VERSION}"
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_LOGIN}"
    - git tag -a "v${VERSION}" -m "CI Auto Tagging"
    - git push origin "v${VERSION}"