image: registry.git.ryuu.technology/docker/gitlabrunners/phpcomposer:latest

services:
  - docker:dind

stages:
- build
- test

variables:
#    CONTAINER_IMAGE: $CI_REGISTRY/docker/gitlabrunners/phpcomposer
#    CONTAINER_IMAGE: registry.git.ryuu.technology/$CI_PROJECT_PATH
    VERSION_MAJOR: 0
    VERSION_MINOR: 0
    VERSION_PATCH: 0

before_script:

build:
    stage: build
    artifacts:
        paths:
        - ./vendor/
    script:
    - composer install
    - ls -lah
    - ls -lah ./vendor/
    
test:
    stage: test
    artifacts:
        paths:
        - ./vendor/
    script:
    - ls -lah
    - ls -lah ./vendor
    - ls -lah ./vendor/bin
    - ./vendor/bin/phpunit --coverage-text --colors=never
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.email "${GITLAB_USER_LOGIN}"
    - git tag -a "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}+${PIPELINE_ID}" -m "CI Auto Tagging"